[package]
name = "usvg-cli"
version = "0.7.0"
authors = ["Reizner Evgeniy <razrfalcon@gmail.com>"]
keywords = ["svg"]
license = "MPL-2.0"
edition = "2018"
description = "An SVG simplification tool."
categories = ["multimedia::images"]
workspace = "../../"

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
fern = "0.5"
log = "0.4"
pico-args = { git = "https://github.com/RazrFalcon/pico-args", rev = "f9e8b51" }
usvg = { version = "0.7.0", path = "../../usvg" }

[[bin]]
name = "usvg"
path = "src/main.rs"
