[package]
name = "rendersvg"
version = "0.2.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"
workspace = "../../"

[dependencies]
failure = "0.1.1"
fern = "0.5"
libflate = "0.1"
log = "0.4"
time = "0.1"

[dependencies.resvg]
path = "../../"

[dependencies.clap]
version = "2"
default-features = false

[features]
cairo-backend = ["resvg/cairo-backend"]
qt-backend = ["resvg/qt-backend"]

[dev-dependencies]
assert_cli = "0.5"
indoc = "0.2"
