[package]
name = "rendersvg"
version = "0.3.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"
workspace = "../../"

[dependencies]
fern = "0.5"
getopts = "0.2"
log = "0.4"
resvg = { path = "../../" }
time = "0.1"

[features]
cairo-backend = ["resvg/cairo-backend"]
qt-backend = ["resvg/qt-backend"]

[dev-dependencies]
assert_cli = "0.5"
indoc = "0.2"
