[package]
name = "rendersvg"
version = "0.9.1"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
fern = "=0.5.8" # fixed version without chrono
log = "0.4"
pico-args = "0.2"
resvg-cairo = { path = "../../resvg-cairo", optional = true }
resvg-qt = { path = "../../resvg-qt", optional = true }
resvg-skia = { path = "../../resvg-skia", optional = true }
resvg-raqote = { path = "../../resvg-raqote", optional = true }
usvg = { path = "../../usvg" }

[features]
default = ["text"]
cairo-backend = ["resvg-cairo"]
qt-backend = ["resvg-qt"]
skia-backend = ["resvg-skia"]
raqote-backend = ["resvg-raqote"]
text = ["usvg/text"] # enables SVG Text support
