[package]
name = "rendersvg"
version = "0.1.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"

[dependencies]
log = "0.4"
fern = "0.5"
derive-error = "0.0.4"
time = "0.1"

[dependencies.svgdom]
# version = "0.10"
git = "https://github.com/RazrFalcon/libsvgdom.git"
#branch = "devel"
rev = "c390d40"
# path = "../../../svgdom"

[dependencies.resvg]
path = "../../"

[dependencies.clap]
version = "2"
default-features = false

[features]
cairo-backend = ["resvg/cairo-backend"]
qt-backend = ["resvg/qt-backend"]

[dev-dependencies]
assert_cli = "0.5"
indoc = "0.2"
