language: rust
rust:
  - stable
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y
  - sudo apt-get update -qq
install:
  # we need gtk3 for capi/examples/cairo
  - sudo apt-get install -y libpango1.0-dev libgtk-3-dev
  - sudo apt-get install -qq qt56base
  # prepare custom Qt
  - source /opt/qt56/bin/qt56-env.sh;
script: ./scripts/run-tests.sh
