[package]
name = "resvg"
version = "0.1.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"
description = "An SVG rendering library."
documentation = "https://docs.rs/resvg/"
repository = "https://github.com/RazrFalcon/resvg"
readme = "README.md"
categories = ["multimedia::images"]

[workspace]
members = [
    "capi",
    "tools/rendersvg"
]
exclude = [
    "examples/cairo-rs",
    "testing_tools",
    "workdir-qt", # for CI tests
    "workdir-cairo" # for CI tests
]

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
euclid = "0.17"
failure = "0.1.1"
log = "0.4"
lyon_geom = "0.10"
usvg = { git = "https://github.com/RazrFalcon/usvg", rev = "7b76247" }
# cairo backend
cairo-rs = { version = "0.4.1", features = ["png"], optional = true }
image = { version = "0.18", default-features = false, features = ["jpeg", "png_codec"], optional = true }
pango = { version = "0.4", optional = true }
pangocairo = { version = "0.5", optional = true }
# qt backend
resvg-qt = { git = "https://github.com/RazrFalcon/resvg-qt", rev = "355fa41", optional = true }

[features]
cairo-backend = ["cairo-rs", "pango", "pangocairo", "image"]
qt-backend = ["resvg-qt"]

[lib]
doctest = false
