[package]
name = "resvg"
version = "0.1.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"
description = "An SVG rendering library."
documentation = "https://docs.rs/resvg/"
repository = "https://github.com/RazrFalcon/resvg"
readme = "README.md"
categories = ["multimedia::images"]

[workspace]
members = [
    "capi",
    "tools/rendersvg"
]
exclude = [
    "examples/cairo-rs",
    "testing_tools",
    "workdir-qt", # for CI tests
    "workdir-cairo" # for CI tests
]

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
base64 = "0.9"
ego-tree = "0.3"
euclid = "0.17"
libflate = "0.1"
log = "0.4"
lyon_geom = "0.10"

[dependencies.error-chain]
version = "0.11"
default-features = false

[dependencies.pango]
version = "0.3"
optional = true

[dependencies.pangocairo]
version = "0.4.1"
optional = true

[dependencies.cairo-rs]
version = "0.3"
features = ["png"]
optional = true

[dependencies.resvg-qt]
git = "https://github.com/RazrFalcon/resvg-qt"
# path = "../resvg-qt"
# version = "0.1.0"
rev = "9a5b017"
optional = true

[dependencies.usvg]
git = "https://github.com/RazrFalcon/usvg"
rev = "299a382"
#path = "../usvg"

[dependencies.svgdom]
# version = "0.10"
git = "https://github.com/RazrFalcon/libsvgdom"
rev = "c390d40"
# path = "../svgdom"

[dependencies.image]
version = "0.18"
default-features = false
features = ["jpeg", "png_codec"]
optional = true

[features]
cairo-backend = ["cairo-rs", "pango", "pangocairo", "image"]
qt-backend = ["resvg-qt"]

[lib]
doctest = false
