[package]
name = "resvg"
version = "0.16.0"
authors = ["Yevhenii Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster", "skia"]
license = "MPL-2.0"
edition = "2018"
description = "An SVG rendering library."
repository = "https://github.com/RazrFalcon/resvg"

[workspace]
members = ["c-api", "svgfilters", "usvg"]

[[bin]]
name = "resvg"
required-features = ["text", "system-fonts", "memmap-fonts"]

[dependencies]
jpeg-decoder = { version = "0.1", default-features = false }
log = "0.4"
pico-args = "0.4"
png = "0.17"
rgb = "0.8"
svgfilters = { path = "svgfilters", version = "0.3" }
tiny-skia = "0.6.1"
usvg = { path = "usvg", version = "0.16.0", default-features = false }

[dev-dependencies]
once_cell = "1.5"

[features]
default = ["text", "system-fonts", "memmap-fonts"]
# enables SVG Text support
text = ["usvg/text"]
# enables system fonts loading (only for `text`)
system-fonts = ["usvg/system-fonts"]
# enables font files memmaping for faster loading (only for `text`)
memmap-fonts = ["usvg/memmap-fonts"]
# enables SVG the --dump-svg flag in CLI
# greatly reduces the binary size when disabled
dump-svg = ["usvg/export"]
