[package]
name = "resvg"
# When updating version, also modify html_root_url in the lib.rs, in the README and in the rendersvg
version = "0.3.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"
description = "An SVG rendering library."
documentation = "https://docs.rs/resvg/"
repository = "https://github.com/RazrFalcon/resvg"
readme = "README.md"
categories = ["multimedia::images"]

[workspace]
members = [
    "capi",
    "tools/rendersvg",
    "examples/cairo-rs",
]
exclude = [
    "examples/cairo-rs",
    "testing_tools",
    "workdir-qt", # for CI tests
    "workdir-cairo", # for CI tests
]

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
log = "0.4.5"
rgb = "0.8.9"
#usvg = "0.2"
usvg = { git = "https://github.com/RazrFalcon/usvg", rev = "1bcd5b7" }
#usvg = { path = "../usvg" }
unicode-segmentation = "1.2.1"

# cairo backend
cairo-rs = { version = "0.5", features = ["png"], optional = true }
gdk-pixbuf = { version = "0.5", optional = true }
pango = { version = "0.5", optional = true }
pangocairo = { version = "0.6", optional = true }

# qt backend
#resvg-qt = { version = "0.3", optional = true }
resvg-qt = { git = "https://github.com/RazrFalcon/resvg-qt", rev = "0fde4c9", optional = true }
#resvg-qt = { path = "../resvg-qt", optional = true }

[features]
cairo-backend = ["cairo-rs", "pango", "pangocairo", "gdk-pixbuf"]
qt-backend = ["resvg-qt"]

[lib]
doctest = false

[profile.release]
lto = true
