[package]
name = "cairo-example"
version = "0.1.0"
authors = ["Reizner Evgeniy <razrfalcon@gmail.com>"]

[dependencies]
gio = "0.4"
gtk = "0.4"
log = "0.4"
fern = "0.5"

[dependencies.resvg]
path = "../.."
features = ["cairo-backend"]
