[package]
name = "cairo-example"
version = "0.1.0"
authors = ["Reizner Evgeniy <razrfalcon@gmail.com>"]
edition = "2018"
workspace = "../.."

[dependencies]
gio = "0.6"
gtk = "0.6"
log = "0.4"
fern = "0.5"

[dependencies.resvg]
path = "../.."
features = ["cairo-backend"]
