[package]
name = "usvg"
# When updating version, also modify html_root_url in the lib.rs and in the ../tools/Cargo.toml
version = "0.6.1"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg"]
license = "MPL-2.0"
edition = "2018"
description = "An SVG simplification library."
categories = ["multimedia::images"]
repository = "https://github.com/RazrFalcon/resvg"
documentation = "https://docs.rs/usvg/"
readme = "README.md"
exclude = ["testing-tools/**"]
workspace = ".."

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
base64 = "0.10"
data-url = "0.1"
harfbuzz_rs = "1.0"
kurbo = "0.2.3"
libflate = "0.1"
log = "0.4"
memmap = "0.7"
rctree = "0.3"
svgdom = "0.17"
ttf-parser = "0.1"
unicode-bidi = "0.3"
unicode-script = "0.3"
unicode-vo = "0.1"

[dev-dependencies]
pretty_assertions = "0.6"
