[package]
name = "resvg-capi"
version = "0.15.0"
authors = ["Yevhenii Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster", "c-api"]
license = "MPL-2.0"
edition = "2018"
workspace = ".."

[lib]
name = "resvg"
path = "lib.rs"
crate-type = ["cdylib", "staticlib"]

[dependencies]
log = "0.4"
resvg = { path = "../" }
usvg = { path = "../usvg", default-features = false }
tiny-skia = "0.5"

[features]
default = ["text", "system-fonts"]
text = ["resvg/text", "usvg/text"] # enables SVG Text support
system-fonts = ["resvg/system-fonts", "usvg/system-fonts"] # enables system fonts loading
