[package]
name = "gtk-ui-rs"
version = "0.1.0"
authors = ["Reizner Evgeniy <razrfalcon@gmail.com>"]
edition = "2018"

# exclude from the parent workspace
[workspace]

[dependencies]
gio = "0.8"
gtk = "0.8"
log = "0.4"
usvg = "0.10"
resvg-cairo = { path = "../.." }
